.TH TERMINIBBLES 1 "March, 2013"
.SH NAME
terminibbles
.SH SYNOPSIS
.B terminibbles
[-pqs] [\-d 123] [-l level-file]
.SH DESCRIPTION
A snake or nibbles game for your terminal.  Includes high-definition text-based
graphics and full-fidelity terminal sound for highly realistic and engaging
gameplay.  Ages 3 and up.
.SH OPTIONS
.TP
.I "\-p"
Progressive difficulty mode.  The game gets harder after every 25 points.
.TP
.I "\-q"
"Quiet" mode.  Doesn't display the splash screen and countdown at startup.
.TP
.I "\-s"
Enable sounds.  Sweet, sweet terminal beeps.
.TP
.I "\-d difficulty"
Set the difficulty level. 1 = easy, 2 = medium, 3 = hard.
.TP
.I "\-l level-file
Load a level file.  level-file can be a path to a specific level file, or
reference one of the levels installed on the system.  If no level-file is given,
installed levels are listed.
.SH CONTROLS
.TP
.I "Movement"
WASD, HJKL, Arrow Keys
.TP
.I "Pause"
p
.TP
.I "Quit"
q
.SH AUTHOR
Matthew Malensek
.SH HOMEPAGE
http://matthew.malensek.net/projects/terminibbles
.SH LICENSE
This software is released under the 2-Clause BSD License.  See LICENSE file for
details.
